import { useState } from "react";
import { api } from "../lib/api";

export function SetupScreen({ onComplete }) {
  const [code,     setCode]     = useState("");
  const [status,   setStatus]   = useState("idle"); // idle | loading | success | error
  const [result,   setResult]   = useState(null);
  const [errorMsg, setErrorMsg] = useState("");
  const [localIp,  setLocalIp]  = useState(() => localStorage.getItem("captain_local_server_ip") || "");
  const [scanning, setScanning] = useState(false);

  async function handleVerify(e) {
    e.preventDefault();
    const trimmed = code.trim().toUpperCase();
    if (!trimmed) return;
    setStatus("loading");
    setErrorMsg("");
    try {
      const data = await api.post("/devices/resolve-link-code", {
        linkCode:   trimmed,
        deviceType: "Plato Captain",
      });
      setResult(data);
      setStatus("success");
    } catch (err) {
      setStatus("error");
      setErrorMsg(err?.message || "Invalid link code — check with your manager.");
    }
  }

  function handleConfirm() {
    const config = {
      outletId:     result.outletId,
      outletCode:   result.outletCode,
      outletName:   result.outletName,
      staff:        result.staff || [],
      configuredAt: new Date().toISOString(),
    };
    localStorage.setItem("captain_branch_config", JSON.stringify(config));
    if (result.deviceToken) localStorage.setItem("captain_token", result.deviceToken);
    const ip = localIp.trim();
    if (ip) localStorage.setItem("captain_local_server_ip", ip);
    else    localStorage.removeItem("captain_local_server_ip");
    onComplete(config);
  }

  async function handleScanForPOS() {
    setScanning(true);
    const subnet = "192.168.1";
    const candidates = Array.from({ length: 20 }, (_, i) => `${subnet}.${i + 1}`);
    for (const ip of candidates) {
      try {
        const res = await fetch(`http://${ip}:4001/plato-pos`, { signal: AbortSignal.timeout(600) });
        if (res.ok) {
          setLocalIp(ip);
          setScanning(false);
          return;
        }
      } catch (_) {}
    }
    setScanning(false);
    alert("POS not found on 192.168.1.x — enter IP manually from POS Settings.");
  }

  return (
    <div className="su2-page">
      <div className="su2-card">
        <div className="su2-logo">
          <svg width="30" height="30" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2.2">
            <circle cx="12" cy="12" r="9"/>
            <path d="M8 12h8" strokeLinecap="round"/>
          </svg>
        </div>

        <h1 className="su2-title">Plato Captain</h1>
        <p className="su2-subtitle">DEVICE SETUP</p>

        {status !== "success" ? (
          <>
            <p className="su2-instruction">
              Enter the branch link code from<br />
              <strong>Owner Web → Outlets → Link Device</strong>
            </p>

            <form className="su2-form" onSubmit={handleVerify}>
              <input
                className={`su2-input${status === "error" ? " su2-input-error" : ""}`}
                type="text"
                value={code}
                onChange={e => { setCode(e.target.value.toUpperCase()); setStatus("idle"); }}
                placeholder="e.g. VNB2-92345678"
                maxLength={20}
                autoFocus
                autoComplete="off"
                spellCheck={false}
              />
              {status === "error" && (
                <p className="su2-error">⚠ {errorMsg}</p>
              )}
              <button
                className="su2-btn"
                type="submit"
                disabled={status === "loading" || !code.trim()}
              >
                {status === "loading" ? (
                  <span style={{ display: "flex", alignItems: "center", gap: 8 }}>
                    <span className="su2-spinner" /> Verifying…
                  </span>
                ) : "Connect to Branch →"}
              </button>
            </form>

            <p className="su2-hint">
              Link code looks like <code>VNB2-92345678</code> — generated by your manager
            </p>
          </>
        ) : (
          <div className="su2-success">
            <div className="su2-check">
              <svg width="26" height="26" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2.5">
                <polyline points="20 6 9 17 4 12"/>
              </svg>
            </div>
            <h2 className="su2-outlet">{result.outletName}</h2>
            <p className="su2-meta">
              {result.tables?.length || 0} tables
              {result.staff?.length ? ` · ${result.staff.length} staff` : ""}
            </p>

            <div className="su2-local">
              <p className="su2-local-label">POS Local IP (optional)</p>
              <p className="su2-local-hint">
                Enter the Windows PC IP shown in POS → Settings. Enables offline floor operations when internet is down.
              </p>
              <div className="su2-local-row">
                <input
                  className="su2-input"
                  type="text"
                  inputMode="decimal"
                  placeholder="e.g. 192.168.1.10"
                  value={localIp}
                  onChange={e => setLocalIp(e.target.value)}
                />
                <button
                  className="su2-scan-btn"
                  type="button"
                  disabled={scanning}
                  onClick={handleScanForPOS}
                >
                  {scanning ? "Scanning…" : "Find POS"}
                </button>
              </div>
            </div>

            <button className="su2-btn" onClick={handleConfirm}>
              Open Plato Captain →
            </button>
            <button
              className="su2-back"
              onClick={() => { setStatus("idle"); setResult(null); setCode(""); }}
            >
              ← Wrong outlet?
            </button>
          </div>
        )}
      </div>
    </div>
  );
}
