import { useEffect, useRef, useState } from "react";
import { io } from "socket.io-client";

import { api }       from "./lib/api";
import { printBill } from "./lib/printBill";
import {
  getStockState,
  subscribeStock,
} from "../../../packages/shared-types/src/stockAvailability.js";
import {
  mobileAreas      as seedAreas,
  mobileCategories as seedCategories,
  mobileMenuItems  as seedMenuItems,
} from "./data/mobile.seed";

// ─── Build areas from outlet tables (like POS does) ──────────────────────────

function buildAreasFromOutlet(outlet) {
  if (!outlet?.tables?.length) return null;
  const areaNames = [...new Set(outlet.tables.map((t) => t.workArea || t.area_name).filter(Boolean))];
  if (!areaNames.length) areaNames.push("Main");
  return areaNames.map((areaName) => {
    const tables = outlet.tables
      .filter((t) => (t.workArea || t.area_name || "Main") === areaName)
      .map((t) => ({
        id:     t.id,
        number: t.table_number || t.tableNumber || t.name,
        seats:  t.seats || 4,
      }));
    return {
      id:     `area-${areaName.toLowerCase().replace(/\s+/g, "-")}`,
      name:   areaName,
      tables,
    };
  });
}

// ─── Branch Config (localStorage) ────────────────────────────────────────────

const CAPTAIN_LS_KEY = "captain_branch_config";

function loadCaptainBranchConfig() {
  try { return JSON.parse(localStorage.getItem(CAPTAIN_LS_KEY) || "null"); }
  catch { return null; }
}
function saveCaptainBranchConfig(cfg) {
  localStorage.setItem(CAPTAIN_LS_KEY, JSON.stringify(cfg));
}
function clearCaptainBranchConfig() {
  localStorage.removeItem(CAPTAIN_LS_KEY);
}

// ─── Branch Setup Screen ──────────────────────────────────────────────────────

function CaptainBranchSetupScreen({ onComplete }) {
  const [code,     setCode]     = useState("");
  const [status,   setStatus]   = useState("idle");
  const [result,   setResult]   = useState(null);
  const [errorMsg, setErrorMsg] = useState("");

  async function handleVerify(e) {
    e.preventDefault();
    const trimmed = code.trim().toUpperCase();
    if (!trimmed) return;
    setStatus("loading");
    setErrorMsg("");
    try {
      const data = await api.post("/devices/resolve-link-code", {
        linkCode:   trimmed,
        deviceType: "Captain App",
      });
      setResult(data);
      setStatus("success");
    } catch (err) {
      setStatus("error");
      setErrorMsg(err?.message || "Invalid link code — check with your manager.");
    }
  }

  function handleConfirm() {
    const config = {
      outletId:     result.outletId,
      outletCode:   result.outletCode,
      outletName:   result.outletName,
      staff:        result.staff || [],
      configuredAt: new Date().toISOString(),
    };
    saveCaptainBranchConfig(config);
    // Save device token so all API calls use the correct tenant
    if (result.deviceToken) {
      localStorage.setItem("captain_token", result.deviceToken);
    }
    onComplete(config);
  }

  return (
    <div className="branch-setup-screen">
      <div className="branch-setup-card">
        <div className="branch-setup-logo" style={{ fontSize: 40 }}>C</div>
        <h1 className="branch-setup-title">Captain App</h1>
        <p className="branch-setup-subtitle">Device Setup</p>

        {status !== "success" ? (
          <>
            <p className="branch-setup-instruction">
              Enter the branch link code from<br />
              <strong>Owner Web → Outlets → Link Device</strong>
            </p>
            <form className="branch-setup-form" onSubmit={handleVerify}>
              <input
                className={`branch-code-input${status === "error" ? " error" : ""}`}
                type="text"
                value={code}
                onChange={e => { setCode(e.target.value.toUpperCase()); setStatus("idle"); }}
                placeholder="e.g. INDR-1001"
                maxLength={20}
                autoFocus
                autoComplete="off"
                spellCheck={false}
              />
              {status === "error" && <p className="branch-setup-error">⚠ {errorMsg}</p>}
              <button
                className="branch-setup-btn"
                type="submit"
                disabled={status === "loading" || !code.trim()}
              >
                {status === "loading" ? "Verifying…" : "Connect to Branch →"}
              </button>
            </form>
            <p className="branch-setup-hint">
              The link code is generated by the outlet manager. It looks like <code>ABCD-1234</code>.
            </p>
          </>
        ) : (
          <div className="branch-setup-success">
            <div className="branch-success-check">✓</div>
            <h2 className="branch-success-name">{result.outletName}</h2>
            <p className="branch-success-meta">
              {result.tables?.length || 0} tables
              {result.staff?.length ? ` · ${result.staff.length} staff` : ""}
            </p>
            <button className="branch-setup-btn success" onClick={handleConfirm}>
              Open Captain App →
            </button>
            <button
              className="branch-setup-back"
              onClick={() => { setStatus("idle"); setResult(null); setCode(""); }}
            >
              ← Wrong outlet?
            </button>
          </div>
        )}
      </div>
    </div>
  );
}

// ─── Staff Profiles (fallback until branch is linked) ────────────────────────

const FALLBACK_STAFF = [
  { id: "s1", name: "Karthik", role: "Captain", pin: "1234", avatar: "K" },
  { id: "s2", name: "Priya",   role: "Waiter",  pin: "2345", avatar: "P" },
  { id: "s3", name: "Rahul",   role: "Waiter",  pin: "3456", avatar: "R" },
  { id: "s4", name: "Devi",    role: "Waiter",  pin: "4567", avatar: "D" },
  { id: "s5", name: "Ravi",    role: "Waiter",  pin: "5678", avatar: "V" },
];

const NUMPAD_KEYS = ["1","2","3","4","5","6","7","8","9","","0","⌫"];

// ─── Constants ────────────────────────────────────────────────────────────────

const QUICK_NOTES = [
  "Less spicy", "No onion", "No garlic", "Extra spicy",
  "Less salt", "No coriander", "Well done", "Half portion"
];

const STATUS_LABEL = { open: "Free", hold: "Hold", bill: "Bill", running: "Running" };

const SEAT_BG   = ["#e5e7eb","#dbeafe","#dcfce7","#fef9c3","#fce7f3"];
const SEAT_TEXT = ["#374151","#1d4ed8","#15803d","#854d0e","#9d174d"];

const AVATAR_COLORS = ["#111317","#1d4ed8","#15803d","#b45309","#7c3aed","#be123c"];
function avatarBg(name = "") { return AVATAR_COLORS[name.charCodeAt(0) % AVATAR_COLORS.length]; }

// ─── Helpers ──────────────────────────────────────────────────────────────────

function parsePriceNumber(v) {
  if (typeof v === "number") return v;
  return Number(String(v || "").replace(/[^\d.]/g, "")) || 0;
}

function buildBlankOrder(table, area) {
  return {
    tableId:       table.id,
    tableNumber:   table.number,
    areaName:      area.name,
    guests:        0,
    items:         [],
    billRequested: false,
    isOnHold:      false,
  };
}

function tableStatusOf(orders, tableId) {
  const o = orders[tableId];
  if (!o?.items?.length) return "open";
  if (o.isOnHold)        return "hold";
  if (o.billRequested)   return "bill";
  return "running";
}

// ─── Screen: Login ────────────────────────────────────────────────────────────

function LoginScreen({ outletName, staff = FALLBACK_STAFF, onLogin, onForgetDevice }) {
  const [selected, setSelected] = useState(null);
  const [pin,      setPin]      = useState("");
  const [error,    setError]    = useState("");
  const [shake,    setShake]    = useState(false);

  function triggerShake() {
    setShake(true);
    setTimeout(() => setShake(false), 500);
  }

  function handleDigit(d) {
    if (pin.length >= 4) return;
    const next = pin + d;
    setPin(next);
    setError("");
    if (next.length === 4) {
      setTimeout(() => {
        if (next === selected.pin) {
          onLogin(selected);
        } else {
          triggerShake();
          setError("Wrong PIN — try again");
          setTimeout(() => setPin(""), 400);
        }
      }, 150);
    }
  }

  function handleDel() {
    setPin((p) => p.slice(0, -1));
    setError("");
  }

  // ── Staff selection ──────────────────────────────────────────────────────
  if (!selected) {
    return (
      <div className="login-page">
        <div className="login-brand">
          <span className="login-brand-mark">C</span>
          <h1 className="login-brand-title">Captain App</h1>
          <p className="login-brand-sub">{outletName || "Select your profile"}</p>
        </div>
        <div className="staff-grid">
          {staff.map((s) => (
            <button
              key={s.id}
              className="staff-card"
              onClick={() => { setSelected(s); setPin(""); setError(""); }}
            >
              <span className="staff-avatar" style={{ background: avatarBg(s.name) }}>
                {s.avatar || s.name?.[0] || "?"}
              </span>
              <span className="staff-name">{s.name}</span>
              <span className="staff-role">{s.role}</span>
            </button>
          ))}
        </div>
        {onForgetDevice && (
          <button
            style={{ marginTop: 24, fontSize: 12, color: "#6b7280", background: "none", border: "none", cursor: "pointer", textDecoration: "underline" }}
            onClick={onForgetDevice}
          >
            Forget this device &amp; re-link
          </button>
        )}
      </div>
    );
  }

  // ── PIN entry ─────────────────────────────────────────────────────────────
  return (
    <div className="login-page">
      <button className="back-btn" style={{ alignSelf: "flex-start", padding: "14px 18px" }}
        onClick={() => { setSelected(null); setPin(""); setError(""); }}>
        ← Back
      </button>

      <div className="pin-profile">
        <span className="pin-avatar" style={{ background: avatarBg(selected.name) }}>
          {selected.avatar}
        </span>
        <p className="pin-name">{selected.name}</p>
        <p className="pin-role-label">{selected.role}</p>
      </div>

      <div className={`pin-dots-row${shake ? " shake" : ""}`}>
        {[0,1,2,3].map((i) => (
          <span key={i} className={`pin-dot${pin.length > i ? " filled" : ""}`} />
        ))}
      </div>

      {error
        ? <p className="pin-error">{error}</p>
        : <p className="pin-hint">Enter your 4-digit PIN</p>
      }

      <div className="numpad">
        {NUMPAD_KEYS.map((k, i) => (
          <button
            key={i}
            className={`numpad-key${k === "" ? " invisible" : ""}${k === "⌫" ? " del-key" : ""}`}
            onClick={() => k === "⌫" ? handleDel() : k && handleDigit(k)}
            disabled={k === ""}
          >
            {k === "⌫" ? (
              <svg width="22" height="22" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2">
                <path d="M21 4H8l-7 8 7 8h13a2 2 0 0 0 2-2V6a2 2 0 0 0-2-2z"/>
                <line x1="18" y1="9" x2="12" y2="15"/>
                <line x1="12" y1="9" x2="18" y2="15"/>
              </svg>
            ) : k}
          </button>
        ))}
      </div>
    </div>
  );
}

// ─── Modal: Table Transfer ────────────────────────────────────────────────────

function TableTransferModal({ currentTableId, areas, orders, onTransfer, onClose }) {
  return (
    <div className="modal-overlay" onClick={onClose}>
      <div className="bottom-sheet" onClick={(e) => e.stopPropagation()}>
        <span className="sheet-handle" />
        <h3 className="sheet-title">Transfer Table</h3>
        <p className="sheet-sub">Move this order to an empty table</p>
        <div className="sheet-body">
          {areas.map((area) => {
            const others = area.tables.filter((t) => t.id !== currentTableId);
            if (!others.length) return null;
            return (
              <div key={area.id} className="sheet-area-block">
                <p className="sheet-area-head">{area.name}</p>
                <div className="transfer-chips">
                  {others.map((t) => {
                    const st = tableStatusOf(orders, t.id);
                    const isOpen = st === "open";
                    return (
                      <button
                        key={t.id}
                        className={`transfer-chip status-${st}${!isOpen ? " disabled" : ""}`}
                        onClick={() => isOpen && onTransfer(currentTableId, t.id)}
                        disabled={!isOpen}
                      >
                        <span className="tc-num">{t.number}</span>
                        <span className="tc-label">{STATUS_LABEL[st] || st}</span>
                      </button>
                    );
                  })}
                </div>
              </div>
            );
          })}
        </div>
      </div>
    </div>
  );
}

// ─── Modal: Table Merge ───────────────────────────────────────────────────────

function TableMergeModal({ currentTableId, currentOrder, areas, orders, onMerge, onClose }) {
  const occupied = [];
  areas.forEach((area) => {
    area.tables.forEach((t) => {
      if (t.id !== currentTableId && (orders[t.id]?.items?.length > 0)) {
        occupied.push({ table: t, area, order: orders[t.id] });
      }
    });
  });

  return (
    <div className="modal-overlay" onClick={onClose}>
      <div className="bottom-sheet" onClick={(e) => e.stopPropagation()}>
        <span className="sheet-handle" />
        <h3 className="sheet-title">Merge Tables</h3>
        <p className="sheet-sub">
          Combine another table's items into&nbsp;
          <strong>Table {currentOrder?.tableNumber}</strong>
        </p>
        <div className="sheet-body">
          {occupied.length === 0 ? (
            <p className="no-items" style={{ padding: "28px 0", textAlign: "center" }}>
              No other occupied tables
            </p>
          ) : (
            occupied.map(({ table, area, order: o }) => {
              const sub = (o.items || []).reduce((s, i) => s + i.price * i.quantity, 0);
              return (
                <button
                  key={table.id}
                  className="merge-row"
                  onClick={() => onMerge(currentTableId, table.id)}
                >
                  <div className="merge-row-info">
                    <strong className="merge-table-num">Table {table.number}</strong>
                    <span className="merge-area-name">{area.name}</span>
                  </div>
                  <div className="merge-row-right">
                    <span className="merge-summary">
                      {o.items?.length || 0} items · ₹{Math.round(sub * 1.05)}
                    </span>
                    <svg width="18" height="18" fill="none" stroke="currentColor" strokeWidth="2.5" viewBox="0 0 24 24">
                      <polyline points="9 18 15 12 9 6"/>
                    </svg>
                  </div>
                </button>
              );
            })
          )}
        </div>
      </div>
    </div>
  );
}

// ─── Screen: Table Floor ──────────────────────────────────────────────────────

function TableScreen({ areas, orders, onSelectTable }) {
  const [activeArea, setActiveArea] = useState(null);
  const visible = activeArea ? areas.filter((a) => a.id === activeArea) : areas;

  return (
    <div className="w-screen">
      {areas.length > 1 && (
        <div className="area-tabs">
          <button className={`area-tab${!activeArea ? " active" : ""}`} onClick={() => setActiveArea(null)}>
            All
          </button>
          {areas.map((a) => (
            <button
              key={a.id}
              className={`area-tab${activeArea === a.id ? " active" : ""}`}
              onClick={() => setActiveArea(a.id)}
            >{a.name}</button>
          ))}
        </div>
      )}
      <div className="table-list">
        {visible.map((area) => (
          <div key={area.id} className="table-area-section">
            <p className="table-area-head">{area.name}</p>
            <div className="table-chips">
              {area.tables.map((table) => {
                const st     = tableStatusOf(orders, table.id);
                const count  = orders[table.id]?.items?.length || 0;
                const amount = (orders[table.id]?.items || []).reduce(
                  (s, i) => s + (i.price || 0) * (i.quantity || 0), 0
                );
                return (
                  <button
                    key={table.id}
                    className={`table-chip status-${st}`}
                    onClick={() => onSelectTable(table.id, area)}
                  >
                    <span className="table-chip-num">{table.number}</span>
                    {count > 0 && <span className="table-chip-badge">{count}</span>}
                    <span className="table-chip-status">{STATUS_LABEL[st]}</span>
                    {amount > 0 && (
                      <span className="table-chip-amount">₹{Math.round(amount * 1.05)}</span>
                    )}
                  </button>
                );
              })}
            </div>
          </div>
        ))}
      </div>
    </div>
  );
}

// ─── Screen: Split Bill ───────────────────────────────────────────────────────

function SplitBillScreen({ order, outletName, onBack }) {
  const [seats,       setSeats]       = useState(2);
  const [assignments, setAssignments] = useState({});

  const items = order.items || [];

  function cycleAssignment(itemId) {
    setAssignments((prev) => {
      const cur  = prev[itemId] ?? 0;
      const next = cur >= seats ? 0 : cur + 1;
      return { ...prev, [itemId]: next };
    });
  }

  function changeSeatCount(n) {
    setSeats(n);
    setAssignments((prev) => {
      const next = { ...prev };
      Object.keys(next).forEach((id) => { if (next[id] > n) next[id] = 0; });
      return next;
    });
  }

  function getItemsForSeat(seatNum) {
    return items.filter((i) => {
      const a = assignments[i.id] ?? 0;
      return seatNum === 0 ? true : (a === 0 || a === seatNum);
    });
  }

  const total = Math.round(items.reduce((s, i) => s + i.price * i.quantity, 0) * 1.05);

  return (
    <div className="w-screen split-screen">
      <div className="split-head">
        <button className="back-btn" onClick={onBack}>← Back</button>
        <div>
          <h2 className="split-title">Split Bill</h2>
          <p className="split-sub">Table {order.tableNumber} · ₹{total} total</p>
        </div>
      </div>

      <div className="split-count-bar">
        <span className="split-count-label">Split between</span>
        <div className="split-count-btns">
          {[2,3,4].map((n) => (
            <button
              key={n}
              className={`split-count-btn${seats === n ? " active" : ""}`}
              onClick={() => changeSeatCount(n)}
            >{n} people</button>
          ))}
        </div>
      </div>

      <p className="split-hint">Tap an item to assign it — grey = shared by all</p>

      <div className="split-item-list">
        {items.map((item) => {
          const seat = assignments[item.id] ?? 0;
          return (
            <button
              key={item.id}
              className="split-item-row"
              onClick={() => cycleAssignment(item.id)}
            >
              <div className="split-item-left">
                <span className="split-item-name">{item.name}</span>
                {item.note && <span className="split-item-note">{item.note}</span>}
              </div>
              <div className="split-item-right">
                <span className="split-item-price">×{item.quantity} · ₹{(item.price * item.quantity).toFixed(0)}</span>
                <span className="split-seat-badge" style={{ background: SEAT_BG[seat], color: SEAT_TEXT[seat] }}>
                  {seat === 0 ? "All" : `P${seat}`}
                </span>
              </div>
            </button>
          );
        })}
      </div>

      <div className="split-print-area">
        <div className="split-print-grid">
          {Array.from({ length: seats }, (_, i) => i + 1).map((n) => {
            const cnt = getItemsForSeat(n).length;
            return (
              <button
                key={n}
                className="waiter-btn split-person-btn"
                onClick={() => { const si = getItemsForSeat(n); if (si.length) printBill(order, si, outletName, { seatLabel: `Person ${n}` }); }}
                disabled={cnt === 0}
              >
                🖨️ Person {n}
                <span className="split-person-count">{cnt} items</span>
              </button>
            );
          })}
        </div>
        <button className="waiter-btn bill" onClick={() => printBill(order, items, outletName)}>
          Print Full Bill
        </button>
      </div>
    </div>
  );
}

// ─── Screen: Order ────────────────────────────────────────────────────────────

function OrderScreen({
  order, tableLabel, categories, menuItems, outletName,
  onBack, onSendKOT, onRequestBill, onPrintBill,
  onToggleHold, onTransfer, onMerge, onUpdateOrder, onAddItem
}) {
  const [screen,      setScreen]      = useState("order");
  const [activeCat,   setActiveCat]   = useState(categories[0]?.id || categories[0]?.name || "");
  const [noteItemIdx, setNoteItemIdx] = useState(null);
  const [noteValue,   setNoteValue]   = useState("");
  const [search,      setSearch]      = useState("");
  const [stockState,  setStockState]  = useState(() => getStockState());

  // Keep stock state in sync with Owner Web / other tabs
  useEffect(() => {
    const unsub = subscribeStock((s) => setStockState({ ...s }));
    return unsub;
  }, []);

  const displayItems = search.trim()
    ? menuItems.filter((i) => i.name.toLowerCase().includes(search.toLowerCase()))
    : menuItems.filter((i) => {
        const cat = i.categoryId || i.category || i.categoryName || "";
        return (cat === activeCat || cat.toLowerCase() === activeCat.toLowerCase()) && i.isActive !== false;
      });

  function addItem(item) {
    const items = [...(order.items || [])];
    const idx   = items.findIndex((i) => i.menuItemId === item.id && !i.sentToKot);
    let itemToSync;
    if (idx >= 0) {
      items[idx] = { ...items[idx], quantity: items[idx].quantity + 1 };
      itemToSync = items[idx];
    } else {
      const newItem = {
        id:         `item-${Date.now()}-${Math.random().toString(16).slice(2,5)}`,
        menuItemId: item.id,
        name:       item.name,
        price:      parsePriceNumber(item.price || item.basePrice),
        quantity:   1,
        sentToKot:  false,
        note:       "",
        station:    item.station || "",
      };
      items.push(newItem);
      itemToSync = newItem;
    }
    onUpdateOrder({ ...order, items });
    onAddItem?.(itemToSync);
    // Stay on menu — user presses "View Order" bar to go back
  }

  function removeOneFromMenu(menuItemId) {
    const items = [...(order.items || [])];
    const idx   = items.findIndex((i) => i.menuItemId === menuItemId && !i.sentToKot);
    if (idx < 0) return;
    if ((items[idx].quantity || 1) <= 1) items.splice(idx, 1);
    else items[idx] = { ...items[idx], quantity: items[idx].quantity - 1 };
    onUpdateOrder({ ...order, items });
  }

  function changeQty(idx, delta) {
    const items  = [...(order.items || [])];
    const newQty = (items[idx]?.quantity || 1) + delta;
    if (newQty <= 0) items.splice(idx, 1);
    else items[idx] = { ...items[idx], quantity: newQty };
    onUpdateOrder({ ...order, items });
  }

  function openNote(idx) {
    setNoteItemIdx(idx);
    setNoteValue(order.items[idx]?.note || "");
    setScreen("note");
  }

  function saveNote() {
    const items = [...(order.items || [])];
    items[noteItemIdx] = { ...items[noteItemIdx], note: noteValue };
    onUpdateOrder({ ...order, items });
    setScreen("order");
  }

  const unsentCount = (order.items || []).filter((i) => !i.sentToKot).length;
  const totalAmount = (order.items || []).reduce((s, i) => s + i.price * i.quantity, 0);
  const hasItems    = (order.items || []).length > 0;

  // ── Split screen ───────────────────────────────────────────────────────────
  if (screen === "split") {
    return <SplitBillScreen order={order} outletName={outletName} onBack={() => setScreen("order")} />;
  }

  // ── Note screen ────────────────────────────────────────────────────────────
  if (screen === "note") {
    const item = order.items?.[noteItemIdx];

    // Parse current value into set of selected chips
    const selectedChips = noteValue
      .split(",")
      .map((s) => s.trim())
      .filter(Boolean);

    function toggleChip(n) {
      const already = selectedChips.includes(n);
      const next = already
        ? selectedChips.filter((c) => c !== n)
        : [...selectedChips, n];
      setNoteValue(next.join(", "));
    }

    return (
      <div className="w-screen note-screen">
        <button className="back-btn" onClick={() => setScreen("order")}>← Back</button>
        <h2 className="note-title">{item?.name}</h2>
        <p className="note-subtitle">Choose one or more instructions</p>
        <div className="quick-notes">
          {QUICK_NOTES.map((n) => (
            <button
              key={n}
              className={`quick-note-chip${selectedChips.includes(n) ? " active" : ""}`}
              onClick={() => toggleChip(n)}
            >{n}</button>
          ))}
        </div>
        <textarea
          className="note-input"
          placeholder="Or type a custom instruction…"
          value={noteValue}
          onChange={(e) => setNoteValue(e.target.value)}
          rows={3}
        />
        <button className="waiter-btn primary" onClick={saveNote}>Save Note</button>
      </div>
    );
  }

  // ── Menu screen ────────────────────────────────────────────────────────────
  if (screen === "menu") {
    return (
      <div className="w-screen menu-screen">
        <div className="menu-head">
          <button className="back-btn" onClick={() => setScreen("order")}>← Back</button>
          <h2>Add Items</h2>
        </div>
        <div className="menu-search-bar">
          <svg width="15" height="15" fill="none" stroke="currentColor" strokeWidth="2" viewBox="0 0 24 24">
            <circle cx="11" cy="11" r="8"/><path d="m21 21-4.35-4.35"/>
          </svg>
          <input
            type="text"
            placeholder="Search menu…"
            value={search}
            onChange={(e) => setSearch(e.target.value)}
          />
          {search && <button onClick={() => setSearch("")}>✕</button>}
        </div>
        {!search && (
          <div className="menu-cat-scroll">
            {categories.map((c) => (
              <button
                key={c.id || c.name}
                className={`menu-cat-chip${activeCat === (c.id || c.name) ? " active" : ""}`}
                onClick={() => setActiveCat(c.id || c.name)}
              >{c.name}</button>
            ))}
          </div>
        )}
        <div className="menu-item-list">
          {displayItems.map((item) => {
            const price    = parsePriceNumber(item.price || item.basePrice);
            const soldOut  = stockState[item.id]?.available === false;
            const cartItem = (order.items || []).find((i) => i.menuItemId === item.id && !i.sentToKot);
            const cartQty  = cartItem ? cartItem.quantity : 0;
            return (
              <div key={item.id} className={`menu-item-row${soldOut ? " item-sold-out" : ""}`}>
                <div className="menu-item-info">
                  {item.isVeg !== undefined && (
                    <span className={`veg-badge ${item.isVeg ? "veg" : "nonveg"}`} />
                  )}
                  <span className="menu-item-name">{item.name}</span>
                  {soldOut && <span className="sold-out-chip">SOLD OUT</span>}
                </div>
                <div className="menu-item-right">
                  {!soldOut && <span className="menu-item-price">₹{price}</span>}
                  {!soldOut && (
                    cartQty > 0 ? (
                      <div className="menu-cart-qty-ctrl">
                        <button className="menu-cart-minus" onClick={() => removeOneFromMenu(item.id)}>−</button>
                        <span className="menu-cart-num">{cartQty}</span>
                        <button className="menu-cart-plus" onClick={() => addItem(item)}>+</button>
                      </div>
                    ) : (
                      <button className="menu-item-add-btn" onClick={() => addItem(item)}>+</button>
                    )
                  )}
                </div>
              </div>
            );
          })}
          {displayItems.length === 0 && <p className="no-items">No items found</p>}
        </div>
        {/* ── Floating cart bar — tap to return to order screen ── */}
        {(() => {
          const allItems   = order.items || [];
          const unsentCnt  = allItems.filter((i) => !i.sentToKot).length;
          const cartTotal  = allItems.reduce((s, i) => s + i.price * i.quantity, 0);
          if (!allItems.length) return null;
          return (
            <div className="menu-cart-bar">
              <button className="menu-cart-btn-main" onClick={() => setScreen("order")}>
                <span>
                  {unsentCnt > 0
                    ? `${unsentCnt} unsent item${unsentCnt > 1 ? "s" : ""}`
                    : `${allItems.length} item${allItems.length > 1 ? "s" : ""} in order`}
                </span>
                <div className="menu-cart-btn-right">
                  <span>₹{Math.round(cartTotal * 1.05)}</span>
                  <span className="menu-cart-chip">View Order →</span>
                </div>
              </button>
            </div>
          );
        })()}
      </div>
    );
  }

  // ── Order screen (main) ────────────────────────────────────────────────────
  return (
    <div className="w-screen order-screen">
      {/* Header */}
      <div className="order-head">
        <div className="order-head-row">
          <button className="back-btn" onClick={onBack}>← Tables</button>
          <div className="order-head-actions">
            {order.isOnHold && <span className="hold-tag">⏸ ON HOLD</span>}
          </div>
        </div>
        <div className="order-head-info">
          <h2 className="order-table-title">{tableLabel}</h2>
          <p className="order-table-sub">
            {order.areaName} ·&nbsp;
            <input
              className="guests-inline"
              type="number" min="0" max="20"
              value={order.guests || ""}
              placeholder="0"
              onChange={(e) => onUpdateOrder({ ...order, guests: Number(e.target.value) })}
            />
            &nbsp;guests
          </p>
        </div>
      </div>

      {/* Item list */}
      <div className="order-item-list">
        {!hasItems && (
          <div className="empty-order">
            <svg width="38" height="38" fill="none" stroke="currentColor" strokeWidth="1.5" viewBox="0 0 24 24" opacity=".3">
              <path d="M9 5H7a2 2 0 0 0-2 2v12a2 2 0 0 0 2 2h10a2 2 0 0 0 2-2V7a2 2 0 0 0-2-2h-2"/>
              <rect x="9" y="3" width="6" height="4" rx="1"/>
              <path d="M9 12h6M9 16h4"/>
            </svg>
            <p>No items yet</p>
            <p className="empty-hint">Tap + Add Items to start the order</p>
          </div>
        )}
        {(order.items || []).map((item, idx) => (
          <div key={item.id || idx} className={`order-row${item.sentToKot ? " sent" : ""}`}>
            <div className="order-row-info">
              <span className="order-row-name">{item.name}</span>
              {item.sentToKot && <span className="kot-badge">KOT ✓</span>}
              {item.note
                ? <button className="note-chip active" onClick={() => !item.sentToKot && openNote(idx)}>{item.note}</button>
                : !item.sentToKot && <button className="note-chip" onClick={() => openNote(idx)}>+ note</button>
              }
            </div>
            <div className="order-row-right">
              {!item.sentToKot ? (
                <div className="qty-row">
                  <button className="qty-mini" onClick={() => changeQty(idx, -1)}>−</button>
                  <span className="qty-val">{item.quantity}</span>
                  <button className="qty-mini" onClick={() => changeQty(idx, +1)}>+</button>
                </div>
              ) : (
                <span className="qty-sent">×{item.quantity}</span>
              )}
              <span className="order-row-price">₹{(item.price * item.quantity).toFixed(0)}</span>
            </div>
          </div>
        ))}
      </div>

      {/* Add items bar */}
      <div className="add-items-bar">
        <button className="add-items-btn" onClick={() => setScreen("menu")}>
          + Add Items
          {unsentCount > 0 && (
            <span className="add-items-badge">{unsentCount}</span>
          )}
        </button>
        {totalAmount > 0 && <span className="running-total">₹{Math.round(totalAmount * 1.05)}</span>}
      </div>

      {/* Action buttons */}
      <div className="order-actions">
        {/* Send KOT */}
        {unsentCount > 0 && (
          <button className="waiter-btn kot" onClick={onSendKOT}>
            🍽️ Send KOT ({unsentCount} item{unsentCount > 1 ? "s" : ""})
          </button>
        )}

        {/* Hold + Print */}
        {hasItems && (
          <div className="action-row-2">
            <button
              className={`waiter-btn half-btn${order.isOnHold ? " hold-active" : " hold-idle"}`}
              onClick={onToggleHold}
            >
              {order.isOnHold ? "▶ Resume" : "⏸ Hold"}
            </button>
            <button className="waiter-btn half-btn print-idle" onClick={onPrintBill}>
              🖨️ Print Bill
            </button>
          </div>
        )}

        {/* Transfer + Merge */}
        <div className="action-row-2">
          <button className="waiter-btn half-btn table-action" onClick={onTransfer}>
            ⇄ Transfer
          </button>
          <button
            className="waiter-btn half-btn table-action"
            onClick={onMerge}
            disabled={!hasItems}
            style={{ opacity: hasItems ? 1 : 0.4 }}
          >
            ⊕ Merge
          </button>
        </div>

        {/* Split Bill */}
        {hasItems && (
          <button className="waiter-btn split-idle" onClick={() => setScreen("split")}>
            ✂ Split Bill
          </button>
        )}

        {/* Request Bill */}
        {hasItems && !order.billRequested && (
          <button className="waiter-btn bill" onClick={onRequestBill}>Request Bill</button>
        )}
        {order.billRequested && (
          <div className="bill-requested-banner">✓ Bill requested — awaiting cashier</div>
        )}
      </div>
    </div>
  );
}

// ─── App root ─────────────────────────────────────────────────────────────────

export function App() {
  const [branchConfig,    setBranchConfig]    = useState(() => loadCaptainBranchConfig());
  const [loggedInStaff,   setLoggedInStaff]   = useState(null);
  const [areas,           setAreas]           = useState(seedAreas);
  const [categories,      setCategories]      = useState(seedCategories);
  const [menuItems,       setMenuItems]       = useState(seedMenuItems);
  const [orders,          setOrders]          = useState({});
  const [selectedTableId, setSelectedTableId] = useState(null);
  const [selectedArea,    setSelectedArea]    = useState(null);
  const [outlet,          setOutlet]          = useState(null);
  const [toast,           setToast]           = useState(null);
  const [showTransfer,    setShowTransfer]    = useState(false);
  const [showMerge,       setShowMerge]       = useState(false);
  const socketRef = useRef(null);

  // Staff from branch config (or fallback)
  const branchStaff = branchConfig?.staff?.length ? branchConfig.staff : FALLBACK_STAFF;

  // ── Bootstrap ──────────────────────────────────────────────────────────────
  useEffect(() => {
    if (!branchConfig) return; // not linked yet
    async function bootstrap() {
      try {
        const outlets = await api.get("/outlets");
        const target  = outlets.find((o) => o.id === branchConfig.outletId) || outlets[0];
        if (!target) return;
        setOutlet(target);

        // Build table areas from this outlet (replaces seed areas)
        const builtAreas = buildAreasFromOutlet(target);
        if (builtAreas) setAreas(builtAreas);

        const [cats, items] = await Promise.all([
          api.get(`/menu/categories?outletId=${target.id}`).catch(() => []),
          api.get(`/menu/items?outletId=${target.id}`).catch(() => []),
        ]);
        if (cats.length)  setCategories(cats);
        if (items.length) setMenuItems(items.map((i) => ({ ...i, price: parsePriceNumber(i.basePrice || i.price) })));

        // Load any orders the backend has (may be partial/empty; POS will push current
        // state via request:order-sync after the socket connects below)
        const liveOrders = await api.get(`/operations/orders?outletId=${target.id}`).catch(() => []);
        if (liveOrders.length) {
          setOrders(Object.fromEntries(liveOrders.map((o) => [o.tableId, o])));
        }
        // Don't overwrite with empty array — keep previous state if backend has nothing

        const socketUrl = (import.meta.env.VITE_API_BASE_URL || "http://localhost:4000/api/v1")
          .replace("/api/v1", "");
        const socket = io(socketUrl, { query: { outletId: target.id } });
        socketRef.current = socket;

        // order:updated — merge single order update (table occupied / cleared / modified)
        socket.on("order:updated", (o) => setOrders((p) => {
          // If the updated order has no items or is closed, treat the table as free
          if (!o.items?.length || o.isClosed) {
            const { [o.tableId]: _removed, ...rest } = p;
            return rest;
          }
          return { ...p, [o.tableId]: o };
        }));

        socket.on("kot:sent", ({ tableId }) =>
          setOrders((p) => {
            if (!p[tableId]) return p;
            return { ...p, [tableId]: { ...p[tableId], items: p[tableId].items.map((i) => ({ ...i, sentToKot: true })) } };
          })
        );
        // ── Owner Web changed menu — re-fetch categories & items ─────────
        socket.on("sync:config", async () => {
          try {
            const [cats, items] = await Promise.all([
              api.get(`/menu/categories?outletId=${target.id}`).catch(() => null),
              api.get(`/menu/items?outletId=${target.id}`).catch(() => null),
            ]);
            if (cats)  setCategories(cats);
            if (items) setMenuItems(items);
          } catch (_) { /* non-critical */ }
        });
      } catch (err) {
        console.error("Waiter bootstrap failed:", err.message);
      }
    }
    bootstrap();
    return () => socketRef.current?.disconnect();
  }, [branchConfig]);

  // ── Utils ──────────────────────────────────────────────────────────────────
  function showToast(msg) { setToast(msg); setTimeout(() => setToast(null), 2400); }

  async function handleSelectTable(tableId, area) {
    // Optimistic: ensure a local order slot exists immediately so the UI can open
    setOrders((prev) => {
      if (prev[tableId]) return prev;
      const t = area.tables.find((x) => x.id === tableId);
      if (!t) return prev;
      return { ...prev, [tableId]: buildBlankOrder(t, area) };
    });
    setSelectedTableId(tableId);
    setSelectedArea(area);
    setShowTransfer(false);
    setShowMerge(false);

    // Fetch real backend order (get-or-create) and reconcile — server wins
    try {
      const serverOrder = await api.get(`/operations/order?tableId=${tableId}`);
      setOrders((prev) => {
        const local = prev[tableId];
        // Preserve any local-only unsent items added before the response came back
        const serverItemIds = new Set((serverOrder.items || []).map((i) => i.id));
        const localOnlyUnsent = (local?.items || []).filter(
          (li) => !li.sentToKot && !serverItemIds.has(li.id)
        );
        return {
          ...prev,
          [tableId]: { ...serverOrder, items: [...(serverOrder.items || []), ...localOnlyUnsent] },
        };
      });
    } catch (err) {
      // TABLE_NOT_FOUND or network error — stay with local blank order (graceful degradation)
      console.warn(`[captain] open table failed for ${tableId}:`, err.message);
    }
  }

  function handleUpdateOrder(nextOrder) {
    setOrders((p) => ({ ...p, [nextOrder.tableId]: nextOrder }));
    socketRef.current?.emit("order:update", { outletId: outlet?.id, order: nextOrder });
  }

  async function handleAddItem(item) {
    const tableId = selectedTableId;
    if (!tableId) return;
    try {
      const serverOrder = await api.post("/operations/order/item", {
        tableId,
        outletId: outlet?.id,
        item: {
          id:          item.id,
          menuItemId:  item.menuItemId,
          name:        item.name,
          price:       item.price,
          quantity:    1,
          note:        item.note || "",
          stationName: item.station || "",
        },
        actorName: loggedInStaff?.name || "Captain",
      });
      // Server-wins reconcile: keep any local-only unsent items added since this call was made
      setOrders((prev) => {
        const local = prev[tableId];
        if (!local) return prev;
        const serverItemIds = new Set((serverOrder.items || []).map((i) => i.id));
        const localOnlyUnsent = (local.items || []).filter(
          (li) => !li.sentToKot && !serverItemIds.has(li.id)
        );
        return {
          ...prev,
          [tableId]: { ...serverOrder, items: [...(serverOrder.items || []), ...localOnlyUnsent] },
        };
      });
    } catch (err) {
      // Graceful degradation: local state already shows the item; backend will reconcile on next table open
      console.warn("[captain] addItem sync failed:", err.message);
    }
  }

  async function handleSendKOT() {
    const order  = orders[selectedTableId];
    if (!order) return;
    const unsent = (order.items || []).filter((i) => !i.sentToKot);
    if (!unsent.length) return;

    // Optimistic: mark all unsent items as sent immediately
    handleUpdateOrder({ ...order, items: order.items.map((i) => ({ ...i, sentToKot: true })) });
    showToast("🍽️ KOT sent to kitchen");

    // Group unsent items by kitchen station (mirrors POS per-station KOT loop)
    const stationGroups = {};
    for (const item of unsent) {
      const key = item.station || "__default__";
      if (!stationGroups[key]) stationGroups[key] = [];
      stationGroups[key].push(item);
    }

    const kotNumber = `KOT-${Date.now()}`;
    let lastServerOrder;
    for (const [stationKey, stItems] of Object.entries(stationGroups)) {
      try {
        const result = await api.post("/operations/kot", {
          outletId:    outlet?.id,
          tableId:     order.tableId,
          tableNumber: order.tableNumber,
          areaName:    order.areaName,
          kotNumber,
          stationName: stationKey === "__default__" ? undefined : stationKey,
          items:       stItems,
          orderId:     order.id,
          actorName:   loggedInStaff?.name || "Captain",
        });
        if (result.order) lastServerOrder = result.order;
      } catch (e) {
        console.error(`[captain] KOT send (${stationKey}):`, e.message);
      }
    }

    // Reconcile with backend order from last KOT response
    if (lastServerOrder) {
      setOrders((prev) => {
        const local = prev[selectedTableId];
        if (!local) return prev;
        const serverItemIds = new Set((lastServerOrder.items || []).map((i) => i.id));
        const localOnlyUnsent = (local.items || []).filter(
          (li) => !li.sentToKot && !serverItemIds.has(li.id)
        );
        return {
          ...prev,
          [selectedTableId]: {
            ...lastServerOrder,
            items: [...(lastServerOrder.items || []), ...localOnlyUnsent],
          },
        };
      });
    }

    // Return to table view after KOT sent
    setSelectedTableId(null);
  }

  async function handleRequestBill() {
    const order = orders[selectedTableId];
    if (!order) return;
    handleUpdateOrder({ ...order, billRequested: true });
    showToast("Bill requested — cashier notified");
    try { await api.post("/operations/bill-request", { outletId: outlet?.id, tableId: selectedTableId }); } catch (_) {}
  }

  function handlePrintBill() {
    const order = orders[selectedTableId];
    if (!order?.items?.length) { showToast("No items to print"); return; }
    printBill(order, order.items, outlet?.name);
    showToast("Printing bill…");
    // Return to table view after bill print
    setSelectedTableId(null);
  }

  function handleToggleHold() {
    const order = orders[selectedTableId];
    if (!order) return;
    const next = { ...order, isOnHold: !order.isOnHold };
    handleUpdateOrder(next);
    showToast(next.isOnHold ? "⏸ Order on hold" : "▶ Order resumed");
  }

  // ── Table Transfer ─────────────────────────────────────────────────────────
  function handleTableTransfer(fromId, toId) {
    const fromOrder = orders[fromId];
    if (!fromOrder) return;

    // Find destination table + area
    let toTable = null, toArea = null;
    for (const area of areas) {
      const t = area.tables.find((x) => x.id === toId);
      if (t) { toTable = t; toArea = area; break; }
    }
    if (!toTable || !toArea) return;

    const movedOrder = { ...fromOrder, tableId: toId, tableNumber: toTable.number, areaName: toArea.name };

    setOrders((prev) => {
      const next = { ...prev };
      // Free old table
      const fromArea = areas.find((a) => a.tables.some((t) => t.id === fromId));
      const fromTable = fromArea?.tables.find((t) => t.id === fromId);
      next[fromId] = fromTable && fromArea ? buildBlankOrder(fromTable, fromArea) : undefined;
      if (!next[fromId]) delete next[fromId];
      // Set new table
      next[toId] = movedOrder;
      return next;
    });

    setSelectedTableId(toId);
    setSelectedArea(toArea);
    setShowTransfer(false);
    showToast(`✓ Order moved to Table ${toTable.number}`);
  }

  // ── Table Merge ────────────────────────────────────────────────────────────
  function handleTableMerge(currentId, mergeFromId) {
    const current   = orders[currentId];
    const mergeFrom = orders[mergeFromId];
    if (!current || !mergeFrom) return;

    const mergedOrder = {
      ...current,
      items:  [...(current.items || []), ...(mergeFrom.items || [])],
      guests: (current.guests || 0) + (mergeFrom.guests || 0),
    };

    // Find mergeFrom table to reset it
    let mfTable = null, mfArea = null;
    for (const area of areas) {
      const t = area.tables.find((x) => x.id === mergeFromId);
      if (t) { mfTable = t; mfArea = area; break; }
    }

    setOrders((prev) => ({
      ...prev,
      [currentId]:   mergedOrder,
      [mergeFromId]: mfTable && mfArea ? buildBlankOrder(mfTable, mfArea) : prev[mergeFromId],
    }));

    const fromNum = mergeFrom.tableNumber || mergeFromId;
    setShowMerge(false);
    showToast(`✓ Table ${fromNum} merged into this order`);
  }

  // ── Derived state ──────────────────────────────────────────────────────────
  const selectedOrder = selectedTableId ? orders[selectedTableId] : null;
  const selectedTable = selectedTableId && selectedArea
    ? selectedArea.tables.find((t) => t.id === selectedTableId) : null;
  const tableLabel = selectedTable ? `Table ${selectedTable.number}` : "";

  // ── Render ─────────────────────────────────────────────────────────────────

  // Branch setup gate (after all hooks)
  if (!branchConfig) {
    return (
      <CaptainBranchSetupScreen
        onComplete={(cfg) => setBranchConfig(cfg)}
      />
    );
  }

  // Login gate
  if (!loggedInStaff) {
    return (
      <LoginScreen
        outletName={outlet?.name || branchConfig.outletName}
        staff={branchStaff}
        onLogin={setLoggedInStaff}
        onForgetDevice={() => {
          clearCaptainBranchConfig();
          setBranchConfig(null);
        }}
      />
    );
  }

  return (
    <div className="waiter-app">
      {/* Header */}
      <header className="waiter-header">
        <div className="waiter-header-inner">
          <div className="waiter-brand">
            <span className="waiter-brand-mark" style={{ background: avatarBg(loggedInStaff.name) }}>
              {loggedInStaff.avatar}
            </span>
            <div>
              <strong>{loggedInStaff.name}</strong>
              <p>{loggedInStaff.role} · {outlet?.name || "Restaurant"}</p>
            </div>
          </div>
          <button className="logout-btn" onClick={() => { setLoggedInStaff(null); setSelectedTableId(null); }}>
            Sign out
          </button>
        </div>
      </header>

      {/* Main content */}
      <main className="waiter-main">
        {!selectedTableId ? (
          <TableScreen areas={areas} orders={orders} onSelectTable={handleSelectTable} />
        ) : (
          <OrderScreen
            order={selectedOrder || buildBlankOrder(
              { id: selectedTableId, number: selectedTableId },
              selectedArea || { name: "" }
            )}
            tableLabel={tableLabel}
            categories={categories}
            menuItems={menuItems}
            outletName={outlet?.name}
            onBack={() => setSelectedTableId(null)}
            onSendKOT={handleSendKOT}
            onRequestBill={handleRequestBill}
            onPrintBill={handlePrintBill}
            onToggleHold={handleToggleHold}
            onTransfer={() => setShowTransfer(true)}
            onMerge={() => setShowMerge(true)}
            onUpdateOrder={handleUpdateOrder}
            onAddItem={handleAddItem}
          />
        )}
      </main>

      {/* Transfer modal */}
      {showTransfer && selectedTableId && (
        <TableTransferModal
          currentTableId={selectedTableId}
          areas={areas}
          orders={orders}
          onTransfer={handleTableTransfer}
          onClose={() => setShowTransfer(false)}
        />
      )}

      {/* Merge modal */}
      {showMerge && selectedTableId && (
        <TableMergeModal
          currentTableId={selectedTableId}
          currentOrder={selectedOrder}
          areas={areas}
          orders={orders}
          onMerge={handleTableMerge}
          onClose={() => setShowMerge(false)}
        />
      )}

      {toast && <div className="waiter-toast">{toast}</div>}
    </div>
  );
}
